# fly.toml app configuration file generated for soshannessy-week3 on 2024-06-11T16:21:19+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'soshannessy-week3'
primary_region = 'syd'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
